services:
  laminarflow:
    container_name: laminarflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      # All runtime environment variables
      - .env
    restart: unless-stopped
    # Optional: if you need to persist any data
    # volumes:
    #   - ./data:/app/data

    # Optional: healthcheck to ensure the app is running
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 10s
      retries: 3